description: "Cloud & DevOps Engineer"
remote_theme: jekyll-theme-hack
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "dark" # Options: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: false
