title: Ashwin Kumar M
description: Cloud & DevOps Engineer | SRE | Ex-Technical Team Lead
theme: jekyll-theme-midnight
show_downloads: false
google_analytics: 

# Customizing the layout
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# User Links (These appear in the sidebar/header automatically in this theme)
github:
  is_project_page: false
